services:
    application:
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        image: application
        container_name: application
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - laravel_app

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_app

    mysql:
        container_name: db
        restart: always
        image: mysql:latest
        platform: linux/x86_64
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASS: root
        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            - laravel_app

networks:
  laravel_app:
    driver: bridge
